#!/bin/bash
set -e

# Server Hardening Script for Hetzner VPS
# Version: 1.0
# Usage: ./harden-server.sh [username] [password]
# If run without args, prompts interactively

NEW_USER=${1:-}
NEW_PASSWORD=${2:-}

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║         HETZNER VPS SERVER HARDENING SCRIPT                  ║"
echo "║                                                              ║"
echo "║  This script will:                                           ║"
echo "║  • Create non-root user with sudo                            ║"
echo "║  • Setup SSH key-only authentication                         ║"
echo "║  • Install & configure fail2ban                              ║"
echo "║  • Setup UFW firewall                                        ║"
echo "║  • Enable automatic security updates                         ║"
echo "║  • Configure timezone                                        ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
  echo "❌ This script must be run as root"
  echo "Usage: sudo $0 [username] [password]"
  exit 1
fi

# Get user input if not provided
if [ -z "$NEW_USER" ]; then
  read -p "Enter new username (default: lavish): " NEW_USER
  NEW_USER=${NEW_USER:-lavish}
fi

if [ -z "$NEW_PASSWORD" ]; then
  echo "Enter password for user '$NEW_USER':"
  read -s NEW_PASSWORD
  echo ""
  echo "Confirm password:"
  read -s NEW_PASSWORD_CONFIRM
  echo ""

  if [ "$NEW_PASSWORD" != "$NEW_PASSWORD_CONFIRM" ]; then
    echo "❌ Passwords don't match"
    exit 1
  fi
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "▶ STEP 1: Creating User '$NEW_USER'"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Create user if doesn't exist
if id "$NEW_USER" &>/dev/null; then
  echo "⚠️  User '$NEW_USER' already exists"
else
  # Create user with home directory
  useradd -m -s /bin/bash "$NEW_USER"
  echo "✓ User created"
fi

# Set password
echo "$NEW_USER:$NEW_PASSWORD" | chpasswd
echo "✓ Password set"

# Add to sudo group
usermod -aG sudo "$NEW_USER"
echo "✓ Added to sudo group"

# Allow passwordless sudo (for automation)
echo "$NEW_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$NEW_USER
chmod 440 /etc/sudoers.d/$NEW_USER
echo "✓ Configured passwordless sudo"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "▶ STEP 2: Copying SSH Keys"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Copy SSH keys from root to new user
if [ -d /root/.ssh ]; then
  mkdir -p /home/$NEW_USER/.ssh
  cp /root/.ssh/authorized_keys /home/$NEW_USER/.ssh/authorized_keys 2>/dev/null || true
  chown -R $NEW_USER:$NEW_USER /home/$NEW_USER/.ssh
  chmod 700 /home/$NEW_USER/.ssh
  chmod 600 /home/$NEW_USER/.ssh/authorized_keys 2>/dev/null || true
  echo "✓ SSH keys copied from root"
else
  echo "⚠️  No SSH keys found in /root/.ssh"
  echo "   Make sure to add your public key to /home/$NEW_USER/.ssh/authorized_keys"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "▶ STEP 3: Configuring SSH Security"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Backup original sshd_config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

# Configure SSH security settings
cat > /etc/ssh/sshd_config.d/99-hardening.conf <<EOF
# SSH Hardening Configuration
# Generated by harden-server.sh on $(date)

# Disable root login
PermitRootLogin no

# Key-based authentication only
PubkeyAuthentication yes
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes

# Disable empty passwords
PermitEmptyPasswords no

# Disable X11 forwarding (not needed)
X11Forwarding no

# Disable TCP forwarding (can enable if needed)
AllowTcpForwarding no

# Limit authentication attempts
MaxAuthTries 3
MaxSessions 5

# Set login grace time
LoginGraceTime 30

# Use strong ciphers only
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256

# Client alive (keep connections alive, detect dead connections)
ClientAliveInterval 300
ClientAliveCountMax 2
EOF

echo "✓ SSH hardening configured"

# Test SSH config before restarting
if sshd -t; then
  echo "✓ SSH config is valid"
else
  echo "❌ SSH config has errors! Reverting..."
  rm /etc/ssh/sshd_config.d/99-hardening.conf
  exit 1
fi

# Restart SSH (will apply new config)
systemctl restart sshd
echo "✓ SSH service restarted"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "▶ STEP 4: Installing & Configuring fail2ban"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Update package list
apt-get update -qq

# Install fail2ban
apt-get install -y fail2ban >/dev/null 2>&1
echo "✓ fail2ban installed"

# Configure fail2ban for SSH
cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
# Ban hosts for 1 hour after 5 failed attempts within 10 minutes
bantime = 3600
findtime = 600
maxretry = 5

# Email notifications (optional - configure if needed)
#destemail = your-email@example.com
#sendername = Fail2Ban
#action = %(action_mwl)s

[sshd]
enabled = true
port = ssh
logpath = %(sshd_log)s
backend = %(sshd_backend)s
maxretry = 3
EOF

# Start and enable fail2ban
systemctl enable fail2ban >/dev/null 2>&1
systemctl start fail2ban
echo "✓ fail2ban configured and started"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "▶ STEP 5: Configuring UFW Firewall"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Install ufw
apt-get install -y ufw >/dev/null 2>&1
echo "✓ ufw installed"

# Reset UFW to default
ufw --force reset >/dev/null 2>&1

# Default policies
ufw default deny incoming
ufw default allow outgoing
echo "✓ Default policies set"

# Allow SSH (CRITICAL - don't lock yourself out!)
ufw allow ssh
echo "✓ SSH allowed (port 22)"

# Allow Clawdbot gateway from localhost only
# (External access can be added later via Hetzner Cloud Firewall if needed)
ufw allow from 127.0.0.1 to any port 18789
echo "✓ Gateway allowed from localhost (port 18789)"

# Enable UFW
ufw --force enable
echo "✓ UFW firewall enabled"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "▶ STEP 6: Configuring Automatic Security Updates"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Install unattended-upgrades
apt-get install -y unattended-upgrades apt-listchanges >/dev/null 2>&1
echo "✓ unattended-upgrades installed"

# Configure automatic updates
cat > /etc/apt/apt.conf.d/50unattended-upgrades <<EOF
Unattended-Upgrade::Allowed-Origins {
    "\${distro_id}:\${distro_codename}";
    "\${distro_id}:\${distro_codename}-security";
    "\${distro_id}ESMApps:\${distro_codename}-apps-security";
    "\${distro_id}ESM:\${distro_codename}-infra-security";
};

Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOF

# Enable and start service
systemctl enable unattended-upgrades
systemctl start unattended-upgrades
echo "✓ Automatic security updates enabled"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "▶ STEP 7: Additional Security Hardening"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Disable unused filesystems
cat > /etc/modprobe.d/disable-filesystems.conf <<EOF
install cramfs /bin/true
install freevxfs /bin/true
install jffs2 /bin/true
install hfs /bin/true
install hfsplus /bin/true
install udf /bin/true
EOF
echo "✓ Disabled unused filesystems"

# Kernel hardening via sysctl
cat > /etc/sysctl.d/99-security.conf <<EOF
# IP Forwarding (disable if not needed)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Ignore send redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Log Martians
net.ipv4.conf.all.log_martians = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Ignore ICMP ping requests (optional - can make debugging harder)
# net.ipv4.icmp_echo_ignore_all = 1

# Increase system file descriptor limit
fs.file-max = 65535
EOF

sysctl -p /etc/sysctl.d/99-security.conf >/dev/null 2>&1
echo "✓ Kernel security parameters applied"

# Set timezone to Europe/Amsterdam (for Lavish Nederland)
timedatectl set-timezone Europe/Amsterdam
echo "✓ Timezone set to Europe/Amsterdam"

# Install additional security tools
apt-get install -y \
  logrotate \
  curl \
  wget \
  git \
  htop \
  >/dev/null 2>&1
echo "✓ Basic tools installed"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "▶ STEP 8: Final Cleanup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Remove unused packages
apt-get autoremove -y >/dev/null 2>&1
apt-get autoclean -y >/dev/null 2>&1
echo "✓ Cleaned up unused packages"

# Update MOTD (Message of the Day)
cat > /etc/motd <<'EOF'
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║          LAVISH NEDERLAND PILOT - PRODUCTION SERVER         ║
║                                                              ║
║  This server runs a 10-agent AI content agency              ║
║  Please be careful with production systems!                 ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

Quick Commands:
  - Gateway status:  sudo systemctl status lavish-gateway
  - View logs:       sudo journalctl -u lavish-gateway -f
  - Health check:    curl http://localhost:18789/health
  - Test agent:      clawdbot agent --agent ceo --message "Test"

EOF
echo "✓ Updated MOTD"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║  ✅ SERVER HARDENING COMPLETE!                               ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Security Features Enabled:"
echo "  ✓ Non-root user created: $NEW_USER"
echo "  ✓ SSH key-only authentication"
echo "  ✓ Root SSH login disabled"
echo "  ✓ fail2ban protecting SSH"
echo "  ✓ UFW firewall active"
echo "  ✓ Automatic security updates enabled"
echo "  ✓ Kernel hardening applied"
echo "  ✓ Timezone: Europe/Amsterdam"
echo ""
echo "⚠️  IMPORTANT SECURITY NOTES:"
echo ""
echo "1. Root SSH is now DISABLED"
echo "   From now on, use: ssh $NEW_USER@<server-ip>"
echo ""
echo "2. Password authentication is DISABLED"
echo "   You can only login with your SSH key"
echo ""
echo "3. If you lose your SSH key, you'll need to use Hetzner Console"
echo "   Keep a backup of your SSH key in a safe place!"
echo ""
echo "4. fail2ban will ban IPs after 3 failed SSH attempts"
echo "   Check bans with: sudo fail2ban-client status sshd"
echo ""
echo "5. UFW firewall is active"
echo "   Only SSH (22) is open from outside"
echo "   Gateway (18789) only accessible from localhost"
echo ""
echo "6. Automatic security updates run daily at 3 AM"
echo "   Server will NOT auto-reboot (you control when to reboot)"
echo ""
echo "Test your new connection before logging out!"
echo "  ssh $NEW_USER@\$(hostname -I | awk '{print \$1}')"
echo ""
